#Each new term in the Fibonacci sequence is generated by adding the previous
#two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not
#exceed four million, find the sum of the even-valued terms.

# solution without recursion

def fibonacci(end):
    x = 0
    y = 1
    z = 0
    count = 0
    while y < end:
        z = x + y
        x = y
        y = z
        if y % 2 == 0:
            count = count + y
    return (count)

end = 4000000

print('The sum until 4000000 is: ', fibonacci(end))
